repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
      exclude: |
        (?x)(
            ^tests/reference/|
            ^src/finchlite/codegen/stc/
        )

    - id: trailing-whitespace
      exclude: |
        (?x)(
            ^tests/reference/|
            ^src/finchlite/codegen/stc/
        )

    - id: mixed-line-ending
      exclude: |
        (?x)(
            ^tests/reference/|
            ^src/finchlite/codegen/stc/
        )

    - id: name-tests-test
      args: ["--pytest-test-first"]
      exclude: |
        (?x)(
            ^tests/reference/|
            ^tests/scripts/|
            ^src/finchlite/codegen/stc/
        )

    - id: no-commit-to-branch

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.14
  hooks:
    - id: ruff-check
      args: [--fix, --config=pyproject.toml]
      types_or: [python, pyi, jupyter]
    - id: ruff-format
      args: [--config=pyproject.toml]
      types_or: [python, pyi, jupyter]

ci:
  autofix_prs: false
